### ISSUE TITLE
question: in the o2m case, perent_id is lower, so i can not get the parent_id, design this for what?

### ISSUE THREAD

**Issue by naivelife** [facebook/ent#992] opened 2020-11-27 05:53 UTC

**Comment by a8m** [comment] 2020-11-28 11:56
Hey @naivelife and thanks for raising up this issue.
That's going to be addressed soon - see discussion in https://github.com/facebook/ent/issues/869.

Closing as it's duplicate of https://github.com/facebook/ent/issues/869.

**Closed by a8m** 2020-11-28 11:56 UTC
