### ISSUE TITLE
Select for update

### ISSUE THREAD

**Issue by wclaro** [facebook/ent#736] opened 2020-09-07 19:42 UTC
Hi guys.

I would like to know if there is a way in ent to use SELECT ... FOR UPDATE in mysql for locking rows.

Thanks for the great work and project

**Comment by a8m** [comment] 2020-09-08 07:16
Hey @wclaro!
We don't support this option at the moment (it may be added in the future).
Closing, since this is duplicate of https://github.com/facebook/ent/issues/358.

**Closed by a8m** 2020-09-08 07:16 UTC
