### ISSUE TITLE
Expose foreign key IDs of 02O and O2M

### ISSUE THREAD

**Issue by rubensayshi** [facebook/ent#1148] opened 2021-01-07 14:36 UTC
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Expose foreign keys of O2O and 02M edges.

ie. a `Pet` entity should have `.OwnerID` as field so you don't have to `pet.Edges.Owner = pet.QueryOwner().OnlyX()` )or eager load it).

This not only saves a subquery for the loading, but also just simplifies a lot of code.

If you think this is something that could be added then I'm happy to put in the work for it!

**Comment by a8m** [comment] 2021-01-07 14:53
Hey @rubensayshi, there's a WIP on this on https://github.com/facebook/ent/pull/1046. 

I'll comment my thoughts there and try to push this ASAP. Closing, as this is duplicate of #869.

**Closed by a8m** 2021-01-07 14:53 UTC

**Comment by rubensayshi** [comment] 2021-01-07 14:59
you're my hero! sorry I hadn't noticed it was a duplicate

**Comment by a8m** [comment] 2021-01-07 15:01
Hehe, thanks for your contributions. It's really appreciated! 😃
