### ISSUE TITLE
Can't have db-generated uuid id primary key with postgres

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [facebook/ent#781] opened 2020-09-18 23:28 UTC
Trying to make a model/schema that has its `id` primary key a `uuid` with a database-defined default value.

This results in a (valid) SQL along the lines of
```sql
insert into tablename (notidcol1, notidcol2) values (?, ?) returning "id"
```

But then this special case code for postgres triggers and it blows up trying to parse the uuid string as an int64 :sob: 
https://github.com/facebook/ent/blob/master/dialect/sql/sqlgraph/graph.go#L1135-L1142

At a first glance, it looks like the `insert` method that calls that from https://github.com/facebook/ent/blob/master/dialect/sql/sqlgraph/graph.go#L876
needs to also pass `c.ID.Type` so it can use a more appropriate scanning function for the actual type of the `id` column, and a corresponding change to the return type of `insertLastID` to also be generic (e.g. as `driver.Value`). `insertLastIDs` and `batchInsert` would need similar updates.

**Comment by a8m** [comment] 2020-09-19 08:44
Hey @mgabeler-lee-6rs and thanks for opening this issue. This is actually a change that I want to add in ent.

> Trying to make a model/schema that has its id primary key a uuid with a database-defined default value.

If you configure something as follows, ent will execute the default-value function before creating the entity in the database.

```go
field.UUID("id", uuid.UUID{}).
	Default(uuid.New)
```

However, setting an expression in the `DEFAULT` clause is not supported at the moment, because only PostgreSQL and MySQL (>= 8.0.13) support it. 

There are a few proposals in the issue tracker about adding support for dialect-specific DDLs using annotations (see #562 and #663). This option can be added as well along with a support for it in ent-runtime (the `sqlgraph` package).

> insertLastIDs and batchInsert would need similar updates.

PostgreSQL will have a special case in batch insert, because it's the only dialect that can return the generated IDs. 

Closing as this is a duplicate of #562.

**Closed by a8m** 2020-09-19 08:44 UTC

**Comment by mgabeler-lee-6rs** [comment] 2021-01-19 06:11
#1104 seems to have implemented this, at least partially
