### ISSUE TITLE
Postgres: edges in different schemas

### ISSUE THREAD

**Issue by TomUnequals** [facebook/ent#801] opened 2020-09-28 11:27 UTC
Since `ent.Config{}` does not support table names in the following format: `<schema>.<table>`, I was wondering how do we create edges to tables in different schemas?

For example, having a user table in one schema which contains user's IDs, whilst having a table in another schema which references those user IDs.

Thanks in advance.

**Comment by a8m** [comment] 2020-09-28 17:52
Hey @TomUnequals!

Currently, this option is supported (yet) by ent, but it's definitely in our roadmap - you can track the progress in #663.

Closing as this is duplicate of #663

**Closed by a8m** 2020-09-28 17:52 UTC
